
export const SKILLS_CATEGORIES = [
  'Network Engineering',
  'Cybersecurity',
  'Data Communication',
  'Telecommunications',
  'Web Development',
  'Mobile App Development',
  'Software Engineering',
  'Artificial Intelligence (AI)',
  'Machine Learning',
  'Data Science',
  'Cloud Computing (AWS/Azure/GCP)',
  'Internet of Things (IoT)',
  '5G Technology',
  'Satellite Communication',
  'Fiber Optics',
  'Blockchain',
  'DevOps',
  'System Administration',
  'Database Management',
  'IT Support & Helpdesk',
  'Digital Signal Processing',
  'Wireless Communication',
  'UI/UX Design',
  'Embedded Systems',
  'Robotics',
  'Information Systems',
];
